package com.anime.watcher.controller;

import com.anime.watcher.exceptions.UserNotFoundException;
import com.anime.watcher.model.User;
import com.anime.watcher.repository.UserRepository;
import org.apache.commons.collections4.IterableUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * @author sei3
 * on 31/07/2021.
 */
@RestController
@RequestMapping(path="/user")
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository repository;



    @GetMapping("/list")
    List<User> all() {
        return IterableUtils.toList(repository.findAll());
    }

    @PostMapping("/add")
    User newUser(@RequestBody User newUser) {
        return repository.save(newUser);
    }

    @PostMapping("/addAdmin")
    User newAdmin(@RequestBody User newUser) {
        newUser.setIs_admin(true);
        return repository.save(newUser);
    }

    @PostMapping("/getUserbyId/{id}")
    User getUserById(@RequestBody Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new UserNotFoundException(id));
    }
}
