package com.sutorimingu.no.sekai.controller;

import com.sutorimingu.no.sekai.model.Comment;
import com.sutorimingu.no.sekai.repository.CommentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.util.Calendar;
import java.util.List;

/**
 * @author sei3
 * on 31/07/2021.
 */
@RestController
@RequestMapping(path="/comment")
public class CommentController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CommentRepository repository;

    @PostMapping("/add")
    Comment newComment(@RequestBody Comment comment) {
        if(comment.getCreator() == null || comment.getAnime() == null){
            throw new RuntimeException("Cannot comment with Anime or no User");
        }
        final Date currentDate = new java.sql.Date(Calendar.getInstance().getTime().getTime());
        comment.setPost_date(currentDate);
        return repository.save(comment);
    }


    @GetMapping("/getCommentByAnime/{id}")
    List<Comment> getUserById(@PathVariable Long id) {
        return repository.findByAnime_Id(id);
    }
}
